### ISSUE TITLE
Launch with error 'KeyError: "['specified_funds'] not in index"'

### ISSUE THREAD

**Issue by tiems90** [whittlem/pycryptobot#156] opened 2021-05-11 23:19 UTC
**Describe the bug**
Errors at launch. It only affects one of my 3 portfolios on startup, as the format doesn't confirm to the specc here:
https://github.com/whittlem/pycryptobot/blob/d530ab7d59364acfd4322f47bfc5ee9af35fe289/models/CoinbasePro.py#L192

**To Reproduce**
1. launch using `python3 pycryptobot.py` 
2. See error

**Error Log**
```python
Traceback (most recent call last):
  File "pycryptobot.py", line 66, in <module>
    orders = account.getOrders(app.getMarket(), '', 'done')
  File "/home/pi/pycryptobot/BTC/models/TradingAccount.py", line 110, in getOrders
    self.orders = model.getOrders(market, action, status)
  File "/home/pi/pycryptobot/BTC/models/CoinbasePro.py", line 195, in getOrders
    df = resp.copy()[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1265, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1315, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['specified_funds'] not in index"
```

I've gone in to actually check the columns of `resp`, and it only contains the following:
```python
['id', 'price', 'size', 'product_id', 'profile_id', 'side', 'type', 'time_in_force', 'post_only', 'created_at', 'done_at', 'done_reason', 'fill_fees', 'filled_size', 'executed_value', 'status', 'settled']
``` 

**Desktop (please complete the following information):**
 - OS: Linux; Debian
 - Version: latest git pull as of 2.0.6 

**Additional context**
Config file, aside from `base_currency` identical to working ones. : 
```json
{
     "coinbasepro" : {
         "api_url" : "https://api.pro.coinbase.com",
         "api_key" : "...",
         "api_secret" : "...",
         "api_passphrase" : "...",
         "config" : {
             "base_currency" : "BTC",
             "quote_currency" : "USD",
             "live" : 1,
             "sellatloss" : 0,
             "granularity": 60
         }
     },
     "telegram" : {
         "token" : "...",
         "client_id" : "..."
     }
}
```

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment] 2021-05-12 06:17
I am also running into this error on Docker. Oddly my bot running BTC-USD runs fine.

Config file:
```
{
    "api_url" : "https://api.pro.coinbase.com",
    "api_key" : "...",
    "api_secret" : "...",
    "api_pass" : "...",
    "config" : {
        "base_currency" : "EOS",
        "quote_currency" : "USD",
        "live" : 1,
        "verbose" : 0,
        "sellatloss" : 0
    }
}
```

**Comment by whittlem** [comment] 2021-05-12 10:07
Are you still getting this issue after the last update? Run "git pull"

**Comment by tiems90** [comment] 2021-05-12 11:54
Hi! Thanks for checking in so quickly!
Yes, still having issues after the latest pull.

```python
Traceback (most recent call last):
  File "pycryptobot.py", line 66, in <module>
    orders = account.getOrders(app.getMarket(), '', 'done')
  File "/home/pi/pycryptobot/BTC/models/TradingAccount.py", line 110, in getOrders
    self.orders = model.getOrders(market, action, status)
  File "/home/pi/pycryptobot/BTC/models/CoinbasePro.py", line 195, in getOrders
    df = resp.copy()[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1265, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1315, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['specified_funds'] not in index"
```

**Comment by tiems90** [comment] 2021-05-12 11:57
Hi! Thanks for the quick check-in!
Yes, still running into issues with the definition here:
https://github.com/whittlem/pycryptobot/blob/d530ab7d59364acfd4322f47bfc5ee9af35fe289/models/CoinbasePro.py#L195

Still the same traceback too:
```python
Traceback (most recent call last):
  File "pycryptobot.py", line 66, in <module>
    orders = account.getOrders(app.getMarket(), '', 'done')
  File "/home/pi/pycryptobot/BTC/models/TradingAccount.py", line 110, in getOrders
    self.orders = model.getOrders(market, action, status)
  File "/home/pi/pycryptobot/BTC/models/CoinbasePro.py", line 195, in getOrders
    df = resp.copy()[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1265, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1315, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['specified_funds'] not in index"
```

**Comment by lesterbx** [comment] 2021-05-12 12:10
Same issue here, apparently the property "specified_funds" is returned only for a single order (GET /orders/<id>) but not for a list of orders (GET /orders). Seen in [https://docs.pro.coinbase.com/#list-orders](Coinbase Api Docs)

**Comment by whittlem** [comment] 2021-05-12 12:11
I will look later and fix it. Thanks.

**Comment by eatsleeproute** [comment] 2021-05-12 13:58
I ran into this issue after making a manual partial sell followed by a transfer in one of my bot portfolios, I worked around it by creating a new portfolio.

**Comment by gasteazi** [comment] 2021-05-12 16:33
Hello, I have the same error. On the same machine it works correctly with binance.
```
Traceback (most recent call last):
  File "/app/pycryptobot.py", line 65, in <module>
    orders = account.getOrders(app.getMarket(), '', 'done')
  File "/app/models/TradingAccount.py", line 110, in getOrders
    self.orders = model.getOrders(market, action, status)
  File "/app/models/CoinbasePro.py", line 195, in getOrders
    df = resp.copy()[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['specified_funds'] not in index"
```
Version 2.0.6 sha256:63b50c6ea6d30a5d7498c3a77f51332f87ab65c6bb09e429f7c4474dc4e004c3

Configuration:

```
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "",
        "api_secret" : "",
        "api_passphrase" : "",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "EUR",
            "live" : 1,
            "sellatloss" : 0,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 1,
            "disabletracker" : 1
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}
```


thank you

**Comment by whittlem** [comment] 2021-05-12 22:00
I've not been able to re-create this issue. I can see in the Coinbase Pro documentation that /orders without a status doesn't return the 'specified_funds' column but my code always returns a status. 

I've added some debug code...

                ### DEBUG CODE ###
                if 'specified_funds' not in resp:
                    print ('If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156')
                    print ('---')
                    print (f'uri: orders?status={status}')
                    print (f'size: {len(resp)}')
                    print (resp)
                    print ('---')
                    return pd.DataFrame()
                ###

If you are still experiencing the issue can you update the Issue with the output above. If you don't want to list your actual orders here can you message it to me on Telegram?

I'm not sure if you know but there is a script-get_orders.py file in the project root. If you run the script it will list your Coinbase Pro and/or Binance orders. This may be helpful in re-creating the issue.

Could it be that you don't have any orders yet for the market?

**Comment by tiems90** [comment] 2021-05-12 22:13
Thanks again for checking. This was on a CoinbasePro portfolio that had previously worked fine.
Right now the bot is working again, but when I run `script-get_orders.py` it does trigger the exception:

```bash
If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156
---
uri: orders?status=done
size: 1
                                     id    price       size product_id                            profile_id side  ... done_reason   fill_fees  filled_size executed_value status settled
0  5247d65b-7409-441c-b075-fdeaf5d89a3e  64090.0  0.0011644    BTC-USD  94ca97a9-a5a0-48e5-ba23-a77b7677f94c  buy  ...      filled  0.37313198    0.0011644      74.626396   done    True

[1 rows x 17 columns]
---
Empty DataFrame
Columns: []
Index: []
Index([], dtype='object')
Traceback (most recent call last):
  File "script-get_orders.py", line 14, in <module>
    app = PyCryptoBot(exchange='binance')
  File "/home/pi/pycryptobot/BTC/models/PyCryptoBot.py", line 1224, in __init__
    raise ValueError('Binance API URL is invalid')
ValueError: Binance API URL is invalid
```

**Comment by tiems90** [comment] 2021-05-12 22:24
In case you wanted the full details of `resp` this is the full content:

```json
{'id': '5247d65b-7409-441c-b075-fdeaf5d89a3e', 'price': '64090.00000000', 'size': '0.00116440', 'product_id': 'BTC-USD', 'profile_id': '94ca97a9-a5a0-48e5-ba23-a77b7677f94c', 'side': 'buy', 'type': 'limit', 'time_in_force': 'GTC', 'post_only': False, 'created_at': '2021-04-14T10:52:57.342779Z', 'done_at': '2021-04-14T10:58:15.799Z', 'done_reason': 'filled', 'fill_fees': '0.3731319800000000', 'filled_size': '0.00116440', 'executed_value': '74.6263960000000000', 'status': 'done', 'settled': True}
```

**Comment by whittlem** [comment] 2021-05-13 10:37
This should be fixed now. Can you confirm?

**Comment by gasteazi** [comment] 2021-05-13 10:40
I receive this message:


```
If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156
---
uri: orders?status=done
size: 1
                                     id       price  ... status settled
0  44ed5c5c-d632-43ad-811c-570800feaa68  0.82450000  ...   done    True
```

**Comment by gasteazi** [comment] 2021-05-13 10:55
I think it's working properly now. Good job. :-)

```
sudo docker container logs ETH-EUR
If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156
---
uri: orders?status=done
size: 1
                                     id       price  ... status settled
0  44ed5c5c-d632-43ad-811c-570800feaa68  0.82450000  ...   done    True

[1 rows x 18 columns]
---
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.0.7                                               |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-13 10:49:26.274896                           |
================================================================================
|          Sell At Loss : True  --sellatloss 1                                 |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : False  --disablebullonly                             |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : False  --disablelog                                  |
|               Tracker : False  --disabletracker                              |
|      Auto restart Bot : False  --autorestart                                 |
================================================================================
* Candlestick Detected: Inverted Hammer ("Weak - Continuation - Bullish Pattern - Up")

2021-05-13 10:00:00 | ETH-EUR | 3600 | Close: 3048.71 | v EMA12/26: 3233.88 < 3311.52 v | v MACD: -77.64 < -49.34 v | WAIT | Last Action: SELL
2021-05-13 10:51:48 | ETH-EUR | 3600 | Current Price: 3064.67
```

**Comment by ChristianBesp** [comment] 2021-05-13 12:10
I can also confirm the initial issue, but the recent version seems to work. Just leaving my output here as well, in case it helps:

```
If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156
---
uri: orders?status=done
size: 1
                                     id       price  ... status settled
0  8dfb2d6a-fed5-455e-9635-08ba72c7e08f  0.82800000  ...   done    True

[1 rows x 17 columns]
```
Thanks for the quick fix, @whittlem !

**Comment by gasteazi** [comment] 2021-05-13 15:51
```
---

--------------------------------------------------------------------------------

| Python Crypto Bot |

--------------------------------------------------------------------------------

| Release : v2.0.8 |

--------------------------------------------------------------------------------

| Bot Mode : LIVE - live trades using your funds! |

| Bot Started : 2021-05-13 15:47:35.323402 |

================================================================================

| Sell At Loss : False --sellatloss 0 |

| Sell At Resistance : False --sellatresistance |

| Trade Bull Only : True --disablebullonly |

| Buy Near High : True --disablebuynearhigh |

| Use Buy MACD : True --disablebuymacd |

| Use Buy OBV : True --disablebuyobv |

| Use Buy Elder-Ray : True --disablebuyelderray |

| Sell Fibonacci Low : True --disablefailsafefibonaccilow |

| Candlestick Reversal : True --disableprofitbankreversal |

| Telegram : True --disabletelegram |

| Log : True --disablelog |

| Tracker : True --disabletracker |

| Auto restart Bot : False --autorestart |

================================================================================

2021-05-13 15:00:00 | ETH-EUR (BULL) | 3600 | Close: 3106.13 | v EMA12/26: 3184.46 < 3258.12 v | v MACD: -73.67 < -68.06 v | v OBV: 38021.5229 (-4.16%) v | ERI: sell | WAIT | Last Action: SELL

If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156

---

uri: orders?status=done

size: 1

id price ... status settled

0 44ed5c5c-d632-43ad-811c-570800feaa68 0.82450000 ... done True

[1 rows x 18 columns]

---

2021-05-13 15:49:36 | ETH-EUR (BULL) | 3600 | Current Price: 3107.0

If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156

---

uri: orders?status=done

size: 1

id price ... status settled

0 44ed5c5c-d632-43ad-811c-570800feaa68 0.82450000 ... done True

[1 rows x 18 columns]

---
```

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment] 2021-05-13 17:47
I am getting the debugging output. The last transaction I made was selling 3 EOS manually. This sale could be the cause of the issue. The bot does seem to run an identify that the last action was sell.
Info:
- Market: Coinbase Pro
- Coin: EOS-USD
- Bot Version: 2.0.7 -- Newer version won't run for another reason
- Method of Running: Docker
- Host OS: Debian

```
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release :                                                      |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-13 12:12:51.308733                           |
================================================================================
|          Sell At Loss : False  --sellatloss 0                                |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : True  --disablebullonly                              |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : True  --disablebuyobv                                |
|     Use Buy Elder-Ray : True  --disablebuyelderray                           |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : True  --disablelog                                   |
|               Tracker : True  --disabletracker                               |
|      Auto restart Bot : False  --autorestart                                 |
================================================================================
2021-05-13 17:00:00 | EOS-USD (BULL) | 3600 | Close: 9.91 | v EMA12/26: 10.56 < 11.0 v | v MACD: -0.44 < -0.42 v | v OBV: 4778523.7999 (-8.44%) v | ERI: sell | WAIT | Last Action: SELL
If you see this message please include this output in the issue: https://github.com/whittlem/pycryptobot/issues/156
---
uri: orders?status=done
size: 1
                                     id        size  ... status settled
0  ----------------------------  3.00000000  ...   done    True
[1 rows x 15 columns]
---

**Comment by whittlem** [comment] 2021-05-13 21:49
Ok, should be fixed now 'specified_funds' does not exist in the response if the order type is 'limit'. I'm assuming you are doing limit buys and sells in addition to what the bot is doing. This is fine but seems the response looks a little different on limit orders.

The fix is this:

                if 'specified_funds' in resp:
                    df = resp.copy()[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]
                else:
                    # manual limit orders do not contain 'specified_funds'
                    df_tmp = resp.copy()
                    df_tmp['specified_funds'] = None
                    df = df_tmp[[ 'created_at', 'product_id', 'side', 'type', 'filled_size', 'specified_funds', 'executed_value', 'fill_fees', 'status' ]]

**Closed by whittlem** 2021-05-13 21:49 UTC
Labels: bug
