### ISSUE TITLE
Hardcoded limits prevent microtransactions

### ISSUE THREAD

**Issue by rcarmo** [whittlem/pycryptobot#196] opened 2021-05-15 21:19 UTC
**Describe the bug**

The hardcoded limits on https://github.com/whittlem/pycryptobot/blob/main/pycryptobot.py#L78 prevent trading on coins with low valuation (for instance, making a $10 purchase of ADA).

**To Reproduce**
1. Try to trade ADA with only $10/£10/€10 fiat coin

**Expected behavior**

Should work, regardless of balance.

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment] 2021-05-16 02:47
This is a repeat of issue #36. Currently the hard coded limit is $50/£50/€50 fiat coin.

**Comment by rcarmo** [comment] 2021-05-16 08:33
Which is indexed to BTC, and does not apply to many other coins…

**Comment by whittlem** [comment] 2021-05-23 22:25
This does sound like a duplicate of https://github.com/whittlem/pycryptobot/issues/36 but the plan is to remove that card coding for all coins. I just need to find time to do it unless someone wants to help.

**Comment by whittlem** [comment] 2021-06-03 10:39
I'm opening a PR for review on this now.

**Closed by whittlem** 2021-06-03 10:39 UTC
Labels: enhancement, feature request
