### ISSUE TITLE
[Coinbase Pro] Size is too accurate (buy and sell: quote_increment vs base_increment)

### ISSUE THREAD

**Issue by iThom** [whittlem/pycryptobot#216] opened 2021-05-21 10:11 UTC
**Describe the bug**

For Coinbase Pro, currently in code we are checking the `base_increment` in `marketBuy` method where it should check the `quote_increment` and `min_market_funds` according to the API documentation: https://docs.pro.coinbase.com/#get-products.

https://github.com/whittlem/pycryptobot/blob/ee8a58309999e8939c17c97640be56fb242fbbb6/models/exchange/coinbase_pro/api.py#L285

And no check is done in the `marketSell` method whereas Coinbase Pro check the `base_increment` and `base_min_size`.

https://github.com/whittlem/pycryptobot/blob/ee8a58309999e8939c17c97640be56fb242fbbb6/models/exchange/coinbase_pro/api.py#L308

We should create a `marketQuoteIncrement` method and use it in `marketBuy` and use the `marketBaseIncrement` method in `marketSell`.

Also it would be good to check the min quantity:
- `min_market_funds` in `marketBuy` (maybe no need to check `max_market_funds` as I guess that not man people will trade 1M$)
- `base_min_size` in `marketSell` (maybe no need to check `base_max_size` as it would be more than 8M$ for BTC nowdays)

The following screenshot was sent by @Revonox on Telegram Dev Channel.

![image](https://user-images.githubusercontent.com/219804/119121242-7ab66300-ba2d-11eb-921a-3ed9e49cbd75.png)

**Comment by Nicolas469** [comment] 2021-05-21 10:21
Duplicate of #201 
I already have done a pull request with a commit to fix this issue: https://github.com/whittlem/pycryptobot/pull/206/commits/8a52e6622bdf02a83951795c48e70c7707adcb23

**Comment by iThom** [comment] 2021-05-21 11:34
It's not solving the problem since the commit you mentionned only use base_increment for both buy and sell where base_increment should only be used for sell and quote_increment for buy.

**Comment by Nicolas469** [comment] 2021-05-21 11:48
You'are right, I'll fix that.

**Comment by Nicolas469** [comment] 2021-05-21 11:51
https://github.com/whittlem/pycryptobot/pull/206/commits/8631c93ca68d9f89e46a342daadc66895b7b2176

**Closed** 2021-05-23 21:51 UTC
Labels: bug, enhancement
