### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by tjgeirk** [whittlem/pycryptobot#458] opened 2021-08-28 03:33 UTC
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
:     with open("README.md", "r", encoding="utf8") as stream:
:   File "/etc/autoPCB/pycryptobot/models/BotConfig.py", line 254, in getVersionFromR>
: Traceback (most recent call last):
: FileNotFoundError(2, 'No such file or directory')

**To Reproduce**
run bot as systemd daemon and activate daemon - then refer to journalctl

ubuntu server 20.04

**Comment by loomsen** [comment] 2021-08-28 07:53
Hi. 

That's not enough info for reproduction. You would at least need to share the unit file you are using.
You'll most likely need to set `WorkingDirectory` in your unit file, but that's just an educated guess.

However, I tend to think this is not a bug, but a misconfiguration on your side. Please refer to the telegram channel if you have futher questions about the bot, and to your distros support channels to get info on how to write systemd unit files. 

Closing this.

**Closed by loomsen** 2021-08-28 07:53 UTC
